[package]
name = "matchum-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Core spell checking logic: word splitting, validation pipeline"

[dependencies]
matchum-dict = { workspace = true }
matchum-config = { workspace = true }
regex = { workspace = true }
aho-corasick = "1"
compact_str = { workspace = true }
hashbrown = { workspace = true }
unicode-xid = { workspace = true }
thiserror = { workspace = true }
typos-dict = "0.13.22"
unicase = "2.9.0"

[dev-dependencies]
insta = { workspace = true }
