[package]
name = "ruspell-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "CLI spell checker compatible with cspell"

[[bin]]
name = "ruspell"
path = "src/main.rs"

[dependencies]
ruspell-core = { workspace = true }
ruspell-dict = { workspace = true }
ruspell-config = { workspace = true }
clap = { workspace = true }
ignore = { workspace = true }
rayon = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
globset = { workspace = true }
regex = { workspace = true }
json5 = { workspace = true }
md-5 = { workspace = true }
